CottonTouch/Controllers/HotelItemPricesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CottonTouch;

namespace CottonTouch.Controllers
{
    public class HotelItemPricesController : Controller
    {
        private CottonTouchDbEntities db = new CottonTouchDbEntities();

        // GET: HotelItemPrices
        public ActionResult Index()
        {
            var hotelItemPrices = db.HotelItemPrices.Include(h => h.Hotel).Include(h => h.Item);
            return View(hotelItemPrices.ToList());
        }

        // GET: HotelItemPrices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelItemPrice hotelItemPrice = db.HotelItemPrices.Find(id);
            if (hotelItemPrice == null)
            {
                return HttpNotFound();
            }
            return View(hotelItemPrice);
        }

        // GET: HotelItemPrices/Create
        public ActionResult Create()
        {
            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name");
            ViewBag.ItemID = new SelectList(db.Items, "ItemID", "Name");
            return View();
        }

        // POST: HotelItemPrices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HIPID,HotelID,ItemID,PricePerItem,VATPercent,VATAmount,DiscAmount")] HotelItemPrice hotelItemPrice)
        {
            if (ModelState.IsValid)
            {
                db.HotelItemPrices.Add(hotelItemPrice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name", hotelItemPrice.HotelID);
            ViewBag.ItemID = new SelectList(db.Items, "ItemID", "Name", hotelItemPrice.ItemID);
            return View(hotelItemPrice);
        }

        // GET: HotelItemPrices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelItemPrice hotelItemPrice = db.HotelItemPrices.Find(id);
            if (hotelItemPrice == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name", hotelItemPrice.HotelID);
            ViewBag.ItemID = new SelectList(db.Items, "ItemID", "Name", hotelItemPrice.ItemID);
            return View(hotelItemPrice);
        }

        // POST: HotelItemPrices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HIPID,HotelID,ItemID,PricePerItem,VATPercent,VATAmount,DiscAmount")] HotelItemPrice hotelItemPrice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotelItemPrice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name", hotelItemPrice.HotelID);
            ViewBag.ItemID = new SelectList(db.Items, "ItemID", "Name", hotelItemPrice.ItemID);
            return View(hotelItemPrice);
        }

        // GET: HotelItemPrices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelItemPrice hotelItemPrice = db.HotelItemPrices.Find(id);
            if (hotelItemPrice == null)
            {
                return HttpNotFound();
            }
            return View(hotelItemPrice);
        }

        // POST: HotelItemPrices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HotelItemPrice hotelItemPrice = db.HotelItemPrices.Find(id);
            db.HotelItemPrices.Remove(hotelItemPrice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CottonTouch/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CottonTouch;

namespace CottonTouch.Controllers
{
    public class HotelsController : Controller
    {
        private CottonTouchDbEntities db = new CottonTouchDbEntities();

        // GET: Hotels
        public ActionResult Index()
        {
            return View(db.Hotels.ToList());
        }

        // GET: Hotels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // GET: Hotels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hotels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HotelID,Name,Address,Telephone,mobile,Notes,Logo,Website")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Hotels.Add(hotel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hotel);
        }

        // GET: Hotels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HotelID,Name,Address,Telephone,mobile,Notes,Logo,Website")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotel);
        }

        // GET: Hotels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hotel hotel = db.Hotels.Find(id);
            db.Hotels.Remove(hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CottonTouch/Controllers/ItemServiceRequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CottonTouch;

namespace CottonTouch.Controllers
{
    public class ItemServiceRequestsController : Controller
    {
        private CottonTouchDbEntities db = new CottonTouchDbEntities();

        // GET: ItemServiceRequests
        public ActionResult Index()
        {
            var itemServiceRequests = db.ItemServiceRequests.Include(i => i.Item).Include(i => i.ServiceRequest);
            return View(itemServiceRequests.ToList());
        }

        // GET: ItemServiceRequests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemServiceRequest itemServiceRequest = db.ItemServiceRequests.Find(id);
            if (itemServiceRequest == null)
            {
                return HttpNotFound();
            }
            return View(itemServiceRequest);
        }

        // GET: ItemServiceRequests/Create
        public ActionResult Create()
        {
            ViewBag.ItemID = new SelectList(db.Items, "ItemID", "Name");
            ViewBag.ServiceRequestID = new SelectList(db.ServiceRequests, "ServiceRequestID", "DocumentAttached");
            return View();
        }

        // POST: ItemServiceRequests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemServiceRequestID,ServiceRequestID,ItemID,QtnSentToLaundry,QtnRecievedAtLaundry,UnitPrice,VATPercent,VATAmount,DiscAmount,NetAmount,Date")] ItemServiceRequest itemServiceRequest)
        {
            if (ModelState.IsValid)
            {
                db.ItemServiceRequests.Add(itemServiceRequest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ItemID = new SelectList(db.Items, "ItemID", "Name", itemServiceRequest.ItemID);
            ViewBag.ServiceRequestID = new SelectList(db.ServiceRequests, "ServiceRequestID", "DocumentAttached", itemServiceRequest.ServiceRequestID);
            return View(itemServiceRequest);
        }

        // GET: ItemServiceRequests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemServiceRequest itemServiceRequest = db.ItemServiceRequests.Find(id);
            if (itemServiceRequest == null)
            {
                return HttpNotFound();
            }
            ViewBag.ItemID = new SelectList(db.Items, "ItemID", "Name", itemServiceRequest.ItemID);
            ViewBag.ServiceRequestID = new SelectList(db.ServiceRequests, "ServiceRequestID", "DocumentAttached", itemServiceRequest.ServiceRequestID);
            return View(itemServiceRequest);
        }

        // POST: ItemServiceRequests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemServiceRequestID,ServiceRequestID,ItemID,QtnSentToLaundry,QtnRecievedAtLaundry,UnitPrice,VATPercent,VATAmount,DiscAmount,NetAmount,Date")] ItemServiceRequest itemServiceRequest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemServiceRequest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ItemID = new SelectList(db.Items, "ItemID", "Name", itemServiceRequest.ItemID);
            ViewBag.ServiceRequestID = new SelectList(db.ServiceRequests, "ServiceRequestID", "DocumentAttached", itemServiceRequest.ServiceRequestID);
            return View(itemServiceRequest);
        }

        // GET: ItemServiceRequests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemServiceRequest itemServiceRequest = db.ItemServiceRequests.Find(id);
            if (itemServiceRequest == null)
            {
                return HttpNotFound();
            }
            return View(itemServiceRequest);
        }

        // POST: ItemServiceRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemServiceRequest itemServiceRequest = db.ItemServiceRequests.Find(id);
            db.ItemServiceRequests.Remove(itemServiceRequest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CottonTouch/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CottonTouch;

namespace CottonTouch.Views.Home
{
    public class ItemsController : Controller
    {
        private CottonTouchDbEntities db = new CottonTouchDbEntities();

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemID,Name,Description,Quantity,UnitPrice")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemID,Name,Description,Quantity,UnitPrice")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CottonTouch/Views/Shared/_Layout.cshtml
@{ if (Session["UserID"] == null)
    {
        Response.Redirect("~/Access/Login");
    }

}

<!DOCTYPE html>
<html>




<head>

    <title>Cotton Touch</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- bootstrap wysihtml5 - text editor -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/admin-lte/css/AdminLTE.css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="~/Content/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/admin-lte/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/admin-lte/css/skins/skin-blue.min.css" rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>


</head>
<body id="MainBody" class="hold-transition skin-blue sidebar-mini">




    <div class="wrapper">
        <!-- Main Header -->
        @*@if (StartupsCMS.Helpers.AuthFuntions.IsValidUser(((User.Identity as System.Security.Claims.ClaimsIdentity)?.FindFirst("preferred_username")?.Value)))
            {*@
        <header class="main-header">
            <!-- Logo -->

            <a href="https://www.cottontouch.co.uk/" target="_blank" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>CT</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Cotton Touch</b></span>
            </a>

            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" id="biztogglen" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">

                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            @*@Html.ActionLink("Sign out", "SignOut", "Home")*@
                            @Html.ActionLink("Sign out", "LogOut", "Access")
                        </li>

                    </ul>
                </div>
                <div class="navbar-custom-menu">
                    <p style="color:white"></p>
                </div>
            </nav>
        </header>



        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->


                <div class="user-panel" style=" height:75px">
                    <div class="pull-left image">
                        <img src="~/Content/images/Logo1.png" alt="Startups logo">
                    </div>
                    <div class="pull-left info">
                        <p >
                            @if (Session["Name"] != null)
                            {@HttpContext.Current.Session["Name"].ToString()}
                        </p>

                        <p style="font-size:10px"><i class="fa fa-circle text-success"></i> Online</p>
                    </div>
                </div>
                <!-- search form(Optional) -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                    </div>
                </form>
                <ul class="sidebar-menu" data-widget="tree">

                    <li class="header">Content Management</li>


                    <li>
            <a href="@Url.Action("Index", "Home") ">

                <i class="fa fa-industry"></i> <span>Dashboard</span>
            </a>
        </li>
                    <li>
                        <a href="@Url.Action("Index", "Hotels") ">

                            <i class="fa fa-industry"></i> <span>Hotels</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Items") ">

                            <i class="fa  fa-cube"></i> <span>Laundry Items</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "HotelItemPrices") ">

                            <i class="fa fa-industry"></i> <span>Laundry Items Pricing </span>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "ServiceRequests") ">

                            <i class="fa fa-cubes"></i> <span>Service Requests</span>
                        </a>
                    </li>
                    @*<li>
                        <a href="@Url.Action("Index", "ItemServiceRequests") ">

                            <i class="fa fa-cubes"></i> <span>Service Requests Invoicing</span>
                        </a>
                    </li>*@
                    @*<li>
                        <a href="@Url.Action("Contact", "Home") ">

                            <i class="fa fa-users"></i> <span>Reports</span>
                        </a>
                    </li>*@



                    <li class="treeview">

                    </li>

                </ul>

                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>

        @*}*@
        <!-- Content Wrapper.Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header(Page header) -->
            <section class="content-header">
            </section>
            <!-- Main content -->

            <section class="content container-fluid">




                @RenderBody()


            </section>

        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">

            <strong>Copyright &copy;  @DateTime.Now.Year <a href="https://www.linkedin.com/in/jaafar-serhan-87497087/?originalSubdomain=lb" target="_blank">Jaafar serhan</a>.</strong> All rights reserved.
        </footer>
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Create the tabs -->
            <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
                <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <!-- Home tab content -->
                <div class="tab-pane active" id="control-sidebar-home-tab">
                    <h3 class="control-sidebar-heading">Recent Activity</h3>
                    <ul class="control-sidebar-menu">
                        <li>
                            <a href="javascript:;">
                                <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                                <div class="menu-info">

                                    <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                                    <p>Will be 23 on April 24th</p>
                                </div>
                            </a>
                        </li>
                    </ul>
                    <!-- /.control-sidebar-menu -->
                    <h3 class="control-sidebar-heading">Tasks Progress</h3>
                    <ul class="control-sidebar-menu">
                        <li>
                            <a href="javascript:;">
                                <h4 class="control-sidebar-subheading">
                                    Custom Template Design
                                    <span class="pull-right-container">
                                        <span class="label label-danger pull-right">70%</span>
                                    </span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                                </div>
                            </a>
                        </li>
                    </ul>
                    <!-- /.control-sidebar-menu -->
                </div>
                <!-- /.tab-pane -->
                <!-- Stats tab content -->
                <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
                <!-- /.tab-pane -->
                <!-- Settings tab content -->
                <div class="tab-pane" id="control-sidebar-settings-tab">
                    <form method="post">
                        <h3 class="control-sidebar-heading">General Settings</h3>
                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                Report panel usage
                                <input type="checkbox" class="pull-right" checked>
                            </label>
                            <p>
                                Some information about this general settings option
                            </p>
                        </div>
                        <!-- /.form-group -->
                    </form>
                </div>
                <!-- /.tab-pane -->
            </div>
        </aside>
        <div class="control-sidebar-bg"></div>
    </div>



    <!-- REQUIRED JS SCRIPTS -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Content/admin-lte/js/adminlte.min.js")
    @RenderSection("scripts", required: false)
    <script src="../../plugins/timepicker/bootstrap-timepicker.min.js"></script>


    <!-- ./wrapper -->
    @*<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/themes/ui-darkness/jquery-ui.min.css" rel="stylesheet">*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/css/bootstrap-multiselect.css" type="text/css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/js/bootstrap-multiselect.js"></script>

    <link href="~/Content/Chosen/chosen.min.css" rel="stylesheet" />
    <script src="~/Scripts/chosen.jquery.min.js"></script>

</body>


</html>

CottonTouch/Views/Shared/_Layout1.cshtml
@{RenderBody();}