CottonTouch/ViewModels/ServiceRequestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CottonTouch.ViewModels
{
    public class ServiceRequestViewModel
    {
        public int ServiceRequestID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> TotalSentItems { get; set; }
        public Nullable<int> TotalRecievedItems { get; set; }
        public bool ClientSignature { get; set; }
        public bool LaundrySignature { get; set; }
        public string DocumentAttached { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }

        public virtual Hotel Hotel { get; set; }



        // items service request



    }
}

CottonTouch/Controllers/ServiceRequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlTypes;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CottonTouch;

namespace CottonTouch.Controllers
{
    public class ServiceRequestsController : Controller
    {
        private CottonTouchDbEntities db = new CottonTouchDbEntities();

        // GET: ServiceRequests
        public ActionResult Index()
        {
            var serviceRequests = db.ServiceRequests.Include(s => s.Hotel);
            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name");
            return View(serviceRequests.ToList());
        }

        // GET: ServiceRequests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceRequest serviceRequest = db.ServiceRequests.Find(id);
            if (serviceRequest == null)
            {
                return HttpNotFound();
            }
            return View(serviceRequest);
        }

        // GET: ServiceRequests/Create
        public ActionResult Create()
        {
            
              ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name");
            //ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name");
            
            ServiceRequest srlist = null;
            srlist = new ServiceRequest();
            //ViewBag.ItemID =   new SelectList(db.Items, "ItemID", "Name");
            ViewBag.ItemID = db.Items.ToList();

            List<ItemServiceRequest> IRSList = null;
            IRSList = new List<ItemServiceRequest>();

            using (db = new CottonTouchDbEntities())
            {
                srlist.IRSList = db.ItemServiceRequests.Where(y => y.ServiceRequestID == srlist.ServiceRequestID).ToList();
           
            return View(srlist);
            }
        }

        // POST: ServiceRequests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "ServiceRequestID,HotelID,TotalSentItems,TotalRecievedItems,ClientSignature,LaundrySignature,DocumentAttached,TotalPrice,ItemQtnstring")] ServiceRequest serviceRequest)
        {
            if (ModelState.IsValid)
            {
                ItemServiceRequest ISP = null;
                List<ItemServiceRequest> ISPlist = null;

                ISP = new ItemServiceRequest();
                ISPlist = new List<ItemServiceRequest>();


                using (db = new CottonTouchDbEntities())
                {

                    serviceRequest.Date = DateTime.Now;
                    db.ServiceRequests.Add(serviceRequest);
                    db.SaveChanges();
                    
                    ISPlist= StringToISRObject(serviceRequest.ItemQtnstring, serviceRequest);
                    double totalPrice = 0;
                    for (int i = 0; i< ISPlist.Count;i++) {
                        totalPrice += (double)ISPlist[i].NetAmount;
                        
                        db.ItemServiceRequests.Add(ISPlist[i]);
                        db.SaveChanges();
                    }

                    serviceRequest.TotalPrice = totalPrice;
                    db.Entry(serviceRequest).State = EntityState.Modified;
                    db.SaveChanges();
                }



                return RedirectToAction("Index");
            }

            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name", serviceRequest.HotelID);
            return View(serviceRequest);
        }


        // GET: ServiceRequests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceRequest serviceRequest = db.ServiceRequests.Find(id);
            if (serviceRequest == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name", serviceRequest.HotelID);
            return View(serviceRequest);
        }

        // POST: ServiceRequests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ServiceRequestID,HotelID,TotalSentItems,TotalRecievedItems,ClientSignature,LaundrySignature,DocumentAttached,TotalPrice")] ServiceRequest serviceRequest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serviceRequest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name", serviceRequest.HotelID);
            return View(serviceRequest);
        }

        // GET: ServiceRequests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceRequest serviceRequest = db.ServiceRequests.Find(id);
            if (serviceRequest == null)
            {
                return HttpNotFound();
            }
            return View(serviceRequest);
        }

        // POST: ServiceRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            List<ItemServiceRequest> isrlist = db.ItemServiceRequests.Where(k => k.ServiceRequestID == id).ToList();
            db.ItemServiceRequests.RemoveRange(isrlist);
            db.SaveChanges();
            ServiceRequest serviceRequest = db.ServiceRequests.Find(id);
            db.ServiceRequests.Remove(serviceRequest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        // GET: ServiceRequests/Edit/5
        public ActionResult GenerateDeliveryNote(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceRequest serviceRequest = db.ServiceRequests.Find(id);
            if (serviceRequest == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name", serviceRequest.HotelID);
            return View(serviceRequest);
        }


        private List<ItemServiceRequest> StringToISRObject(string str, ServiceRequest serviceRequest)
        {
           
            List<string> ListofItemsQtn = null;
            ListofItemsQtn = new List<string>();
            ListofItemsQtn = str.Split(',').ToList<string>();

            ItemServiceRequest isr = null;
            List<ItemServiceRequest> isrlist = null;
            isrlist = new List<ItemServiceRequest>();

            for (int i = 0; i < ListofItemsQtn.Count; i++) {
                isr = new ItemServiceRequest();
                int itemid = int.Parse(ListofItemsQtn[i]);
                var item = db.Items.Where(s => s.ItemID == itemid).FirstOrDefault();
                var hotel = db.Hotels.Where(f => f.HotelID == serviceRequest.HotelID).FirstOrDefault();
                var hotelitemprice = db.HotelItemPrices.Where(f => f.ItemID== itemid && f.HotelID == serviceRequest.HotelID ).FirstOrDefault();
               
                isr.ItemID = (int?) item.ItemID;
                isr.ServiceRequestID = serviceRequest.ServiceRequestID;
                isr.QtnSentToLaundry = int.Parse(ListofItemsQtn[i + 1]);
                isr.QtnRecievedAtLaundry = int.Parse(ListofItemsQtn[i + 1]);

                if (hotelitemprice == null)
                {
                    isr.UnitPrice = item.UnitPrice; 
                }
                else
                {
                    isr.UnitPrice = hotelitemprice.PricePerItem;
                    isr.VATAmount = hotelitemprice.VATAmount;
                    isr.VATPercent = hotelitemprice.VATPercent;
                    isr.DiscAmount = hotelitemprice.DiscAmount;
                }
                isr.Date = DateTime.Now;
                isr.NetAmount = isr.UnitPrice * isr.QtnSentToLaundry;

                isrlist.Add(isr);
                i += 1;
            }
            return isrlist;
        }

        public ActionResult DeliveryNote(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceRequest serviceRequest = db.ServiceRequests.Find(id);
            if (serviceRequest == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelID = new SelectList(db.Hotels, "HotelID", "Name", serviceRequest.HotelID);
            return View(serviceRequest);
        }


        [HttpGet]
        public ActionResult DeliveryNoteInvoice(string hotelid = "", string from= "", string  to="")
        {
            ViewBag.hotelidstring = hotelid;
            ViewBag.fromstring    = from;
            ViewBag.tostring      = to;


            List<string> todatelst = to.Split(',').ToList<string>();
            List<string> fromdatelst = from.Split(',').ToList<string>();

CottonTouch/Views/ServiceRequests/Create.cshtml
@model CottonTouch.ServiceRequest

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>



    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")*@



    @using (Html.BeginForm( ))
    {
        @*@Html.AntiForgeryToken()*@



        
        





    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Select Hotel and Add Laundry Items to make The Delivery Note</h3>


            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                @*<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>*@
            </div>
        </div>

        <!-- /.box-header -->
        <div class="box-body">

            <div class="box-body no-padding">
                <div class="mailbox-controls">

                    <div class="col-12">

                        @Html.LabelFor(model => model.HotelID, "Hotel", htmlAttributes: new { @Placeholder = "select sth", @class = "control-label col-md-12" })

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.DropDownList("HotelID", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.HotelID, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br clear="all" />
                    </div>
                    <br />
                    <br />
                    <div col="col-12">
                        <table id="submissionTable" class="table table-bordered">
                            <thead>
                                <tr>
                                    <td>Laundry Item Name   </td>
                                    <td>Quantity</td>
                                </tr>
                            </thead>

                            <tr id="tablerow0">
                                <td>
                                    <div class="editor-field">

                                        @*<input class="text-box single-line" name="LaundryItemName[0]" type="text" value="" required="required" />*@

                                        <select class="form-control valid valid" id="ItemID0" name="ItemID0" aria-invalid="false" required>
                                            <option value="0">Select Laundry Item</option>
                                            @{ foreach (var item in ViewBag.ItemID)
                                                {
                                                    <option value="@item.ItemID">@item.Name</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </td>
                                <td>
                                    <div class="editor-field">
                                        <input class="text-box single-line" name="Quantity0" type="text" value="" required />
                                    </div>
                                </td>

                                <td>
                                    <button type="button" class="btn btn-primary" onclick="removeTr(0);">Delete</button>
                                </td>
                                <td></td>
                            </tr>

                        </table>
                        <p>
                            <button id="add" type="button" class="btn btn-primary">Add</button>
                        </p>
                        <p>
                            <button id="Confirm" type="button" onclick="confirmDN()" class="btn btn-primary">Confirm</button>
                        </p>
                        <hr />
                        @Html.Hidden("ItemQtnstring", "")
                        <p>
                            <input type="submit" value="Create" class="btn btn-default" />
                        </p>
                    </div>
                    <!-- /.table -->
                </div>
                <!-- /.mail-box-messages -->
            </div>

        </div>
        <!-- /.box-body -->
    </div>

        @*<p id="DNlist" name="DNlist"> </p>*@



     


    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>



    <!-- page script -->
    <script>
        var totalprice = 0.0;
        var itemsQTN = 0;






      
         var options =document.getElementById('ItemID0').options;
        var optionstring = '';
        var i;
        for (i = 0; i < options.length; i++) {
            optionstring += '<option value="' + options[i].value + '">' + options[i].text + '</option>'
}


        var counter = 1;
        $(function () {
            $('#add').click(function () {


                $(' <tr id="tablerow'+counter+'">'+
                    '<td>'+
                    '<div class="editor-field">'+
                    '<select class= "form-control valid valid" id = "ItemID'+counter+'" name = "ItemID'+counter+'" aria - invalid="false" required > '+ optionstring +'</select>'+
                    '</div>'+
                    '</td>'+
                    '<td>'+
                    '<div class="editor-field">'+
                    '<input class="text-box single-line" id="Quantity'+counter+'"  name="Quantity'+counter+'" type="text" value="" required="required">'+
                    '</div>'+
                     '</td>'+
                     '<td>'+
                     '<button type="button" class="btn btn-primary" onclick="removeTr('+counter+');">Delete</button>'+
                     '</td>'+
                     '<td></td>'+
                     '</tr>').appendTo('#submissionTable');
                counter++;
                return false;
            });
        });
        function removeTr(index) {
            if (counter > 1) {
                $('#tablerow' + index).remove();
                counter--;
            }
            return false;
        }


        var DNlist=[]
        var DNstring;


        function confirmDN() {

            DNlist = [];

            var DNlength = submissionTable.rows.length ;
            var text = "";
             var i;
            for (i = 1; i < DNlength; i++) {

                //document.getElementById("Quantity" + i).disabled = true;
                // document.getElementById("ItemID"+i).disabled=true;
                $("Quantity" + i).attr('disabled', 'disabled');
                $("ItemID" + i).attr('disabled', 'disabled');
                var Quantityinput = $('input:text[name=Quantity' + (i - 1) + ']').val();
                var ItemsSelect = document.getElementById("ItemID" + (i - 1)).value;

                DNstring = ItemsSelect + ',' + Quantityinput;
                DNlist.push(DNstring);
                DNstring = "";
         

            }
            var paragraph = document.getElementById("DNlist");
           var x= DNlist.toString();
            document.getElementById("ItemQtnstring").value = x;

            alert(DNlist);
        }

          $(function () {
            //$('#example1').DataTable()
            //$('#example2').DataTable({
            //    'paging': true,
            //    'lengthChange': false,
            //    'searching': true,
            //    'ordering': true,
            //    'info': true,
            //    'autoWidth': false
            //})
        })
    </script>



</body>

</html>

CottonTouch/Views/ServiceRequests/Delete.cshtml
@model CottonTouch.ServiceRequest

@{
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>ServiceRequest</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TotalSentItems)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TotalSentItems)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TotalRecievedItems)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TotalRecievedItems)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ClientSignature)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ClientSignature)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LaundrySignature)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LaundrySignature)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DocumentAttached)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DocumentAttached)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TotalPrice)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Hotel.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Hotel.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

CottonTouch/Views/ServiceRequests/Details.cshtml
@model CottonTouch.ServiceRequest

@{
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>ServiceRequest</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TotalSentItems)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TotalSentItems)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TotalRecievedItems)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TotalRecievedItems)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ClientSignature)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ClientSignature)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LaundrySignature)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LaundrySignature)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DocumentAttached)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DocumentAttached)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TotalPrice)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Hotel.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Hotel.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ServiceRequestID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

CottonTouch/Views/ServiceRequests/Index.cshtml
@model IEnumerable<CottonTouch.ServiceRequest>

@{
    ViewBag.Title = "Index";}



<style>

    .fa {
        display: inline-block;
        font: normal normal normal 14px/1.5 FontAwesome !important;
        font-size: inherit;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
</style>

<br />

<div class="box box-primary">


    <div class="box-header with-border">
        <h3 class="box-title"><i class="fa fa-list-alt"></i> <span>Delivery Notes List</span></h3>
        <div class="box-tools pull-right">
        </div>

    </div>





    <!-- /.box-tools -->
    <!-- /.box-header -->
    @using (Html.BeginForm())
    {
        <div class="text-left">
            @Html.ActionLink("Create New Delivery Note", "Create", "ServiceRequests", null, new { @class = "btn btn-success" })



            @*@Html.ActionLink("Make Invoice", "DeliveryNoteInvoice", "ServiceRequests", null, new { @onclick = "gotoinvoice()", @class = "btn btn-success" })*@



            @*<button type="submit" id="btn-export-excel" class="btn btn-success btn-sm">Export To Excel</button>*@

            @*<button type="submit" id="btn-export-excel" class="btn btn-success btn-sm">Export To Excel</button>*@


        </div>
        <br />
        <div class="box" style="background: gainsboro">
            <div class="box-header" style="background: darkgray;">
                <h3 class="box-title" style="color:black">Make Invoice  <small >(Open Exapnder)</small></h3>
                <br />

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" style="background:white" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    @*<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>*@
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

                <div class="box-body no-padding">
                    <div class="mailbox-controls">
                        <div class="col-12">
                            <div class="col-4">

                                <label class="control-label col-md-2"> Hotel</label>
                                <div class="form-group">
                                    <div class="col-md-10">
                                        @Html.DropDownList("HotelID", null, htmlAttributes: new { @class = "form-control" })
                                    </div>
                                </div>
                                <br clear="all" />
                            </div>

                            <div class="col-4">

                                <label class="control-label col-md-2"> From Date:</label>
                                <div class="form-group">
                                    <div class="col-md-10">
                                        <input class="form-control" type="text" id="from">
                                    </div>
                                </div>
                                <br clear="all" />
                            </div>

                            <div class="col-4">

                                <label class="control-label col-md-2"> TO Date:</label>
                                <div class="form-group">
                                    <div class="col-md-10">
                                        <input class="form-control" type="text" id="to">
                                    </div>
                                </div>
                                <br clear="all" />
                            </div>

                        </div>

                        <br /> <a class="invoices btn btn-success" href="#" title="Make Invoice"><span>Make Invoice</span></a>
                        <br />
                    </div>
                    <!-- /.mail-box-messages -->
                </div>

            </div>
            <!-- /.box-body -->
        </div>

        <br />
        <div class="no-padding">

            <div class="mailbox-controls">
                <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                    <table id="demoGrid" class="table table-striped table-bordered dt-responsive " width="100%" cellspacing="0">
                        <thead>


                            <tr>

                                <th>
                                    @Html.DisplayName("Delivery Note ID")
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Hotel.Name)
                                </th>


                                <th>
                                    @Html.DisplayNameFor(model => model.TotalPrice)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Date)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ServiceRequestID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Hotel.Name)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.TotalPrice)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Date)
                                </td>
                                <td>

                                    <div class="tools" style="width:100px">

                                        @*<a class="btn btn-primary btn-xs" href="@Url.Action("Edit", "ServiceRequests", new { id = item.ServiceRequestID})"><i class="fa fa-pencil"></i></a>*@
                                        @*<a class="btn btn-primary btn-xs" href="@Url.Action("Details", "ServiceRequests", new { id = item.ServiceRequestID})"><i class="fa fa-list"></i></a>*@
                                        <a class="btn btn-primary btn-xs" href="@Url.Action("DeliveryNote", "ServiceRequests", new { id = item.ServiceRequestID})"><i class="fa fa-print"></i></a>

                                        <a class="btn btn-danger btn-xs" href="@Url.Action("Delete", "ServiceRequests", new { id = item.ServiceRequestID})"><i class="fa fa-trash"></i></a>

                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>


                </div>

                <!-- /.table -->
            </div>
            <!-- /.mail-box-messages -->
        </div>

    }



</div>

<!-- /.box-body -->
<div class="box-footer no-padding">

</div>



<script type="text/javascript">
    /* Create an array with the values of all the checkboxes in a column */
   
      //$('input[type=text]').change(function () {

      //  gotoinvoice();

      //});
        $(function() {
    $("#to").datepicker({
        onSelect: function(dateText, inst) {
gotoinvoice();        }
    });
});
    $(function() {
    $("#from").datepicker({
        onSelect: function(dateText, inst) {
gotoinvoice();        }
    });
});
//    $('#from').change(function(){
//     //Change code!
//        gotoinvoice();

//    });
//     $('#to').change(function(){
//     //Change code!
//         gotoinvoice();
//});
    $(function () {
        $("#from").datepicker();
    });
     $(function () {
        $("#to").datepicker();
    });

  

    function gotoinvoice() {
        var fromdate = document.getElementById("from").value;
        var todate = document.getElementById("to").value;
        var hotelid = document.getElementById("HotelID").value;
     todate = todate.replace(/\//g, ",");
        fromdate = fromdate.replace(/\//g, ",");



              $('.invoices').attr('href', 'http://localhost/CottonTouch/ServiceRequests/DeliveryNoteInvoice?from='+fromdate+'&to='+todate+'&hotelid='+hotelid);


    }

       $('#demoGrid').DataTable({
        "paging": true,
        "pageLength": 50,
        "pagingType": "full_numbers",
           "scrollX": true,    
        "paging": true,
        "searching": true

    });

</script>